#name: REST Assured Tests
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v2
#
#      - name: Set up JDK
#        uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#
#      - name: Build and Test
#        run: mvn clean test
#
#      - name: Generate Allure Report
#        run: |
#          mkdir -p allure-results
#          mvn allure:report
